v1.1 major refactoring

diff --git a/root-shell b/root-shell
--- a/root-shell
+++ b/root-shell
@@ -7,36 +7,44 @@
 #--             Bugs: info@vlastimilburian.cz              --
 #--             GitHub: rebrand.ly/root-shell              --
 #--                      License: MIT                      --
-#--                 Version: 1.0 (stable)                  --
-#--                 Released: 2023-Nov-03                  --
+#--                 Version: 1.1 (stable)                  --
+#--                 Released: 2023-Nov-08                  --
 #------------------------------------------------------------
+
+# You may customize this to e.g.: "sudo -i", or even "su",...
+readonly root_command="sudo -s"
 
 set -o nounset -o errexit
 
-error() { printf >&2 '%s\n' "$@"; exit 1; }
+error()
+{
+    printf >&2 '%s\n' "$@"
+    exit 1
+}
 
 usage()
 {
-    # shellcheck disable=SC2016
     error \
         "Usage of $(basename "$0") script:" \
-        '' \
-        'Starts a root shell using `sudo -s`, no argument accepted.'
+        "" \
+        "Starts a root shell using '$root_command', no argument accepted."
 }
 
-check_dependency() { command -v sudo >/dev/null 2>&1; }
-
-if ! check_dependency; then
-    # shellcheck disable=SC2016
-    printf >&2 '%s\n\n' '`sudo` is required by this script.'; usage
+if [ "$#" -gt 0 ]
+then
+    usage
 fi
 
-if [ "$#" -gt 0 ]; then usage; fi
+if [ "$(id -u)" -eq 0 ]
+then
+    error "You are already superuser."
+fi
 
-is_root() { [ "$(id -u)" -eq 0 ]; }
+if ! command -v sudo >/dev/null 2>&1
+then
+    printf >&2 '%s\n\n' "'sudo' is required by this script."
+    usage
+fi
 
-if is_root; then error 'You are already superuser.'; fi
-
-start_root_shell() { exec sudo -s; }
-
-start_root_shell
+# start root shell
+exec $root_command
